/*
 Copyright 2020 The Knative Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	rest "k8s.io/client-go/rest"
	v1alpha2 "razee.dev/razee/pkg/apis/razee/v1alpha2"
	"razee.dev/razee/pkg/client/clientset/versioned/scheme"
)

type DeployV1alpha2Interface interface {
	RESTClient() rest.Interface
	RemoteResourceS3sGetter
}

// DeployV1alpha2Client is used to interact with features provided by the deploy.razee.io group.
type DeployV1alpha2Client struct {
	restClient rest.Interface
}

func (c *DeployV1alpha2Client) RemoteResourceS3s(namespace string) RemoteResourceS3Interface {
	return newRemoteResourceS3s(c, namespace)
}

// NewForConfig creates a new DeployV1alpha2Client for the given config.
func NewForConfig(c *rest.Config) (*DeployV1alpha2Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &DeployV1alpha2Client{client}, nil
}

// NewForConfigOrDie creates a new DeployV1alpha2Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *DeployV1alpha2Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new DeployV1alpha2Client for the given RESTClient.
func New(c rest.Interface) *DeployV1alpha2Client {
	return &DeployV1alpha2Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha2.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *DeployV1alpha2Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
