/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	time "time"

	razeev1alpha2 "github.com/dvasilen/razee-rrs3/pkg/apis/razee/v1alpha2"
	versioned "github.com/dvasilen/razee-rrs3/pkg/client/clientset/versioned"
	internalinterfaces "github.com/dvasilen/razee-rrs3/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/dvasilen/razee-rrs3/pkg/client/listers/razee/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RemoteResourceS3Informer provides access to a shared informer and lister for
// RemoteResourceS3s.
type RemoteResourceS3Informer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.RemoteResourceS3Lister
}

type remoteResourceS3Informer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRemoteResourceS3Informer constructs a new informer for RemoteResourceS3 type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRemoteResourceS3Informer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRemoteResourceS3Informer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRemoteResourceS3Informer constructs a new informer for RemoteResourceS3 type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRemoteResourceS3Informer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha2().RemoteResourceS3s(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeployV1alpha2().RemoteResourceS3s(namespace).Watch(context.TODO(), options)
			},
		},
		&razeev1alpha2.RemoteResourceS3{},
		resyncPeriod,
		indexers,
	)
}

func (f *remoteResourceS3Informer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRemoteResourceS3Informer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *remoteResourceS3Informer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&razeev1alpha2.RemoteResourceS3{}, f.defaultInformer)
}

func (f *remoteResourceS3Informer) Lister() v1alpha2.RemoteResourceS3Lister {
	return v1alpha2.NewRemoteResourceS3Lister(f.Informer().GetIndexer())
}
