/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/dvasilen/razee-rrs3/pkg/apis/razee/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRemoteResourceS3s implements RemoteResourceS3Interface
type FakeRemoteResourceS3s struct {
	Fake *FakeDeployV1alpha2
	ns   string
}

var remoteresources3sResource = schema.GroupVersionResource{Group: "deploy.razee.io", Version: "v1alpha2", Resource: "remoteresourcess3"}

var remoteresources3sKind = schema.GroupVersionKind{Group: "deploy.razee.io", Version: "v1alpha2", Kind: "RemoteResourceS3"}

// Get takes name of the remoteResourceS3, and returns the corresponding remoteResourceS3 object, and an error if there is any.
func (c *FakeRemoteResourceS3s) Get(name string, options v1.GetOptions) (result *v1alpha2.RemoteResourceS3, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(remoteresources3sResource, c.ns, name), &v1alpha2.RemoteResourceS3{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.RemoteResourceS3), err
}

// List takes label and field selectors, and returns the list of RemoteResourceS3s that match those selectors.
func (c *FakeRemoteResourceS3s) List(opts v1.ListOptions) (result *v1alpha2.RemoteResourceS3List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(remoteresources3sResource, remoteresources3sKind, c.ns, opts), &v1alpha2.RemoteResourceS3List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.RemoteResourceS3List{ListMeta: obj.(*v1alpha2.RemoteResourceS3List).ListMeta}
	for _, item := range obj.(*v1alpha2.RemoteResourceS3List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested remoteResourceS3s.
func (c *FakeRemoteResourceS3s) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(remoteresources3sResource, c.ns, opts))

}

// Create takes the representation of a remoteResourceS3 and creates it.  Returns the server's representation of the remoteResourceS3, and an error, if there is any.
func (c *FakeRemoteResourceS3s) Create(remoteResourceS3 *v1alpha2.RemoteResourceS3) (result *v1alpha2.RemoteResourceS3, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(remoteresources3sResource, c.ns, remoteResourceS3), &v1alpha2.RemoteResourceS3{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.RemoteResourceS3), err
}

// Update takes the representation of a remoteResourceS3 and updates it. Returns the server's representation of the remoteResourceS3, and an error, if there is any.
func (c *FakeRemoteResourceS3s) Update(remoteResourceS3 *v1alpha2.RemoteResourceS3) (result *v1alpha2.RemoteResourceS3, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(remoteresources3sResource, c.ns, remoteResourceS3), &v1alpha2.RemoteResourceS3{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.RemoteResourceS3), err
}

// Delete takes name of the remoteResourceS3 and deletes it. Returns an error if one occurs.
func (c *FakeRemoteResourceS3s) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(remoteresources3sResource, c.ns, name), &v1alpha2.RemoteResourceS3{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRemoteResourceS3s) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(remoteresources3sResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.RemoteResourceS3List{})
	return err
}

// Patch applies the patch and returns the patched remoteResourceS3.
func (c *FakeRemoteResourceS3s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.RemoteResourceS3, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(remoteresources3sResource, c.ns, name, pt, data, subresources...), &v1alpha2.RemoteResourceS3{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.RemoteResourceS3), err
}
